name: Make PDF booklet of Drinks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Running Layout Builder and Check Output
      id: validate
      run: |
        output=$(python Scripts/LayoutBuilder.py)
        echo "::set-output name=result::$output"
        if [[ "$output" == *"Success: Document created."* ]]; then
          echo "Document Created Successfully!"
        else
          echo "Document Creation Failed!"
          echo "$output"
          exit 1
        fi

    - name: Post-validation Success Message
      if: success()
      run: echo "Document created successfully! Continuing with the workflow."

    - name: Post-validation Failure Message
      if: failure()
      run: echo "Document creation failed! Check the details above for errors."

    - name: Update README with Last Updated Date
      if: success()
      run: |
        DATE=$(date)
        sed -i "s/Last updated:.*/Last updated: $DATE/" README.md
        echo "README updated with the last updated date."

    - name: Commit and Push Changes
      if: success()
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README with last updated date [skip ci]"
        git push "https://${GH_PAT}@github.com/${{ github.repository }}.git" HEAD:main

